name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: https://data.forgejo.org/actions/checkout@v6
      - name: setup jdk
        uses: https://github.com/actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: read mod version
        id: version
        run: echo "value=$(awk -F= '/^mod_version=/{print $2}' gradle.properties)" >> "${FORGEJO_OUTPUT:-$GITHUB_OUTPUT}"
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture latest jar artifact
        uses: https://data.forgejo.org/actions/upload-artifact@v7
        with:
          name: mob_life-${{ steps.version.outputs.value }}
          path: build/libs/*-${{ steps.version.outputs.value }}.jar
          if-no-files-found: error
